---
  - name: "update and upgrade apt packages"
    become: true
    apt:
      update_cache: yes
      upgrade: yes

  - name: "remove un-needed dependecies"
    become: true
    apt:
      autoremove: yes
  
  - name: "install dependecies"
    become: true
    apt:
      name: ["nodejs", "npm"]
      state: latest
      update_cache: yes

  - name: "install pm2"
    become: true
    npm:
      name: pm2
      global: yes
      production: yes
      state: present

  - name: Install a list of packages
    become: true
    apt:
      pkg:
      - zip
      - gzip
      - tar
