---
- name: "install pm2"
  become: true
  become_method: sudo
  become_user: root
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "unarchive into the server"
  unarchive:
    src: files/artifact.tar.gz
    dest: ~/

- name: "executing node"
  become: true
  become_method: sudo
  become_user: root 
  shell: |
    pm2 stop default
    pm2 start npm -- start